# Generated by Django 4.0.4 on 2022-05-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movieID',
            new_name='movieId',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movieID',
            new_name='movieId',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='userID',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='userID',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
