# Generated by Django 4.0.4 on 2022-05-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='movieId',
            new_name='movieid',
        ),
    ]
